export const Screens = {
  BOTTOM_NAV: 'BOTTOM_NAV',
  HOME_STACK_NAV: 'HOME_STACK_NAV',
  FAV_STACK_NAV: 'FAV_STACK_NAV',

  HOME_SCREEN: 'HOME_SCREEN',
  PRODUCT_DETAILS_SCREEN: 'PRODUCT_DETAILS_SCREEN',
  CART_SCREEN: 'CART_SCREEN',
  FAV_SCREEN: 'FAV_SCREEN',

  CATEGORY_SCREEN: 'CATEGORY_SCREEN',
  MORE_SCREEN: 'MORE_SCREEN',
}
